myApp/blueprints/user/routes.py
from flask import Flask, redirect, url_for, render_template, request, session, flash, Blueprint, jsonify
from flask import current_app as app
from myApp import db
from myApp.models import User, Exercise, WorkoutPlan, WorkoutDay, PR
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
from flask_login import login_user, logout_user, login_required, current_user
from datetime import datetime


user_bp = Blueprint('user_bp', __name__)

@user_bp.route("/")
def home():
    return render_template("home.html")



@user_bp.route("/login/", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        user_email = request.form.get("email")
        password = request.form.get('password')
        
        user = User.query.filter_by(email=user_email).first()

        if user and check_password_hash(user.password_hash, password):
            login_user(user, remember=True)
            flash("Login Successful!")
            return redirect(url_for("user_bp.user"))
        else:
            flash("Invalid email or password", "error")
            return redirect(url_for("user_bp.login"))    
    else:
        if current_user.is_authenticated:
            flash("Already logged in!")
            return redirect(url_for("user_bp.user"))

        return render_template("login.html")

    

@user_bp.route("/signup/", methods=["POST", "GET"])
def signup():
    if request.method == "POST":    ## if the user enters there info ie a POST method
        name = request.form.get("username")     ## init the name and email var to the info entered on the html form
        email = request.form.get("email")
        password = request.form.get("password")

        #checkif user already exists
        existing_user = User.query.filter_by(email=email).first()      

        if existing_user:
            flash("User already exists. PLease log in or use a different email")
            return redirect(url_for("user_bp.signup"))
        new_user = User(name, email, password)       ## once we have all the info we need to create a user obj we init it as a new user
        
        try:
            db.session.add(new_user)        ## push the user into the db
            db.session.commit() 
            flash("Signup Succesful please login with your new credentials!")
            return redirect(url_for("user_bp.login"))
        except IntegrityError:
            db.session.rollback()
            flash("ERROR: Unable to create user. Please try again later!")
            return redirect(url_for("user_bp.signup"))

    return render_template("signup.html")       ## if the request is just a get ie when a user just goes to the site (A GET request) we just render the html page

@user_bp.route("/user/", methods=["POST", "GET"])
@login_required
def user():
    user = current_user
    return render_template("user.html", user=user)


@user_bp.route("/logout/")
@login_required
def logout():
    logout_user()
    flash("You have succesfully logged out!")
    return redirect(url_for("user_bp.login"))

@user_bp.route("/view/")    ## views login info for all users the password for all users is 'pass'
def view():
    users = User.query.all()
    return render_template("view.html", users=users)

# myApp/user/routes.py

@user_bp.route("/delete_user/<int:user_id>", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash(f"User {user.username} deleted successfully.", "success")
    else:
        flash(f"User not found.", "error")
    return redirect(url_for("user_bp.view"))


@user_bp.route("/create_workoutPlan/", methods=["GET", "POST"])
@login_required
def create_workoutPlan():
    if request.method == "POST":
        name = request.form.get("name")
        cycle_type = request.form.get("cycle_type")
        cycle_length_str = request.form.get("cycle_length")
        
        if not name or not cycle_type or not cycle_length_str:
            flash("Please fill out the form in its entirety!")
            return redirect(url_for("user_bp.create_workoutPlan"))

        try:
            cycle_length = int(cycle_length_str)

        except ValueError:
            flash("Invalid cycle length")
            return redirect(url_for("user_bp.create_workoutPlan"))

        user_id = current_user._id
        
        new_workoutPlan = WorkoutPlan(name, user_id,cycle_type, cycle_length)
        db.session.add(new_workoutPlan)
        db.session.commit()
        
        for day_number in range(1, cycle_length + 1):
            workout_day = WorkoutDay(workout_plan_id=new_workoutPlan._id, day_number=day_number)
            db.session.add(workout_day)
        db.session.commit()
        flash("WorkoutPlan succesfully Created!")
        
    return render_template("create_workoutPlan.html")

@user_bp.route("/view_workoutPlan/", methods=["GET", "POST"])
@login_required
def view_workoutPlan():
    user_id = current_user._id
    plans = WorkoutPlan.query.filter_by(user_id=user_id).all() 
    return render_template("view_workoutPlans.html", plans=plans)

@user_bp.route("/edit_workoutPlans/<int:plan_id>", methods=["GET", "POST"])
@login_required
def edit_workoutPlans(plan_id):
    user_id = current_user._id
    plan = WorkoutPlan.query.get_or_404(plan_id)
    if request.method == "POST":
        if 'update' in request.form:
            plan.name = plan.request.form.get('name', plan.name)
            plan.cycle_type = plan.request.form.get('cycle_type', plan.cycle_type)
            plan.cycle_length = plan.request.form.get('cycle_length', plan.cycle_length)
            db.session.commit()
        elif 'delete' in request.form:
            db.session.delete(plan)
            db.session.commit()
            return redirect(url_for('view_workoutPlans'))
    return render_template("edit_workoutPlans", plan=plan)


@user_bp.route("/edit_workoutPlan/<int:plan_id>", methods=["GET", "POST"])
@login_required
def edit_workoutPlan(plan_id):
    workout_plan = WorkoutPlan.query.get_or_404(plan_id)
    if workout_plan.user_id != current_user._id:
        flash("You do not have permission to edit this workout plan.")
        return redirect(url_for("user_bp.view_workoutPlan"))
    
    return render_template("workout_planEdit.html", workout_plan=workout_plan)

@user_bp.route("/create_exercise/<int:workoutday_id>", methods=["GET", "POST"])
@login_required
def create_exercise(workoutday_id):
    if request.method == "POST":
        name = request.form.get("name")
        description = request.form.get("description")
        weight = request.form.get("weight", None)
        unit = request.form.get("unit", None)

        if not name or not description:
            flash("Name and Description are required.")
            return redirect(url_for("user_bp.create_exercise", workoutday_id=workoutday_id))
        
        user_id = current_user._id
        
        new_exercise = Exercise(name=name, description=description, weight=weight, unit=unit, user_id=user_id)
        workout_day = WorkoutDay.query.get(workoutday_id)
        if workout_day:
            workout_day.exercises.append(new_exercise)
            db.session.add(new_exercise)
            db.session.commit()
            flash("Exercise logged")
            
            plan_id = workout_day.workout_plan_id
            return redirect(url_for("user_bp.edit_workoutPlan", plan_id=plan_id))   
        
        flash("Workout day not found")
        return redirect(url_for("user_bp.create_exercise", workoutday_id=workoutday_id))


@user_bp.route("/edit_exercise/<int:workoutday_id>", methods=["GET", "POST"])
@login_required
def edit_exercise(workoutday_id):
    workout_day = WorkoutDay.query.get_or_404(workoutday_id)
    workout_plan = WorkoutPlan.query.get_or_404(workout_day.workout_plan_id)
    if request.method == "POST":
        exercise_id = request.form.get('exercise_id')
        exercise = Exercise.query.get_or_404(exercise_id)
        
        if 'update' in request.form:    
            if exercise in workout_day.exercises:
                exercise.name = request.form.get("name", exercise.name)
                exercise.description = request.form.get("description", exercise.description)
                exercise.weight = request.form.get("weight", exercise.weight)
                exercise.unit = request.form.get("unit", exercise.unit)
                db.session.commit()
                flash("Exercise Succesfully Updated!", 'success')
        elif 'delete' in request.form:
            if exercise in workout_day.exercises:
                workout_day.exercises.remove(exercise)
                db.session.delete(exercise)
                db.session.commit()
                flash("Exercise Deleted Successfully!", 'success')
        
    
    return render_template("workout_planEdit.html", workout_plan=workout_plan)


@user_bp.route("/log_pr/", methods=["GET", "POST"]) ## blank for now
@login_required
def log_pr():
    if request.method == "POST":
        exercise_name = request.form.get("name")
        weight = request.form.get("weight")
        unit = request.form.get("unit")
        date_str = request.form.get("date")
        
        if not exercise_name:
            flash("Name is a required field!")
            return redirect(url_for("user_bp.log_pr"))

        user_id = current_user._id
        try:
            date = datetime.strptime(date_str, "%Y-%m-%d")
        except ValueError:
            flash("Invalid date format!")
            return redirect(url_for("user_bp.log_pr"))

        pr = PR(user_id=user_id ,exercise_name=exercise_name, weight=weight, unit=unit, date=date)

        db.session.add(pr)
        db.session.commit()

        flash("PR Logged")
        return redirect(url_for("user_bp.user"))
    return render_template("log_pr.html")

@user_bp.route("/view_prs/", methods=["GET", "POST"])

myApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Fitness Tracker</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signup">Signup</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    

    <div class="container-fluid">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-info" role="alert">
              {% for msg in messages %}
                  {{ msg }}
              {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
      {% block content %}
      
      {% endblock %}
    </div>
    
    <footer>
      <p>&copy; 2024 Fitness Tracker. All rights reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>  
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

myApp/templates/createExercise.html
{% extends "base.html" %}
{% block title %}Exercise Creation Page{% endblock %}

{% block content %}
    <head><link rel="stylesheet" href="{{ url_for('static', filename='createExercise.css') }}"></head>

    <body>
        <div class="container">
            <h1>Create Exercise Entry</h1>
            <form method="POST" action="{{ url_for('user_bp.create_exercise') }}">
                <div class="form-group">
                    <label for="name">Exercise Name:</label>
                    <input type="text" id="name" name="name" class="form-control" required>
                </div>
                
                <div class="form-group">
                    <label for="description">Description:</label>
                    <input type="text" id="description" name="description" class="form-control" required>
                </div>
                
                <div class="form-group">
                    <label for="weight">Weight:</label>
                    <input type="number" id="weight" name="weight" class="form-control">
                </div>
                
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="datetime-local" id="date" name="date" class="form-control">
                </div>
                
                <button type="submit" class="btn btn-primary">Create Exercise</button>
            </form>
            <br>
            <a href="{{ url_for('user_bp.user') }}" class="btn btn-secondary">Back to Profile</a>
        </div>
    </body>


{% endblock %}

myApp/templates/create_workoutPlan.html
{% extends "base.html" %}

{% block title %}Create Workout Plan{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Create Workout Plan</h2>
            <form action="{{ url_for('user_bp.create_workoutPlan') }}" method="post">
                <div class="form-group mb-3">
                    <label for="name">Plan Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter workout plan name" required>
                </div>
                <div class="form-group mb-3">
                    <label for="cycle_type">Cycle Type</label>
                    <input type="text" class="form-control" id="cycle_type" name="cycle_type" placeholder="e.g., Push-Pull-Legs" required>
                </div>
                <div class="form-group mb-3">
                    <label for="cycle_length">Cycle Length (days)</label>
                    <input type="number" class="form-control" id="cycle_length" name="cycle_length" placeholder="Enter number of days in cycle" required>
                </div>
                <button type="submit" class="btn btn-primary">Create Plan</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

myApp/templates/home.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}
{% block content %}
    <head><link rel="stylesheet" href="{{ url_for('static', filename='css/homePage.css') }}"></head>
    
    <section class="hero">
        <div class="container text-center">
            <h2 class="hero-title">Track Your Fitness Goals</h2>
            <p class="hero-description">Stay fit, stay motivated. Achieve your fitness goals with our easy-to-use fitness tracker.</p>
            <a href="/signup/" class="cta-button btn btn-primary">Get Started</a>
        </div>
    </section>

    <section class="features py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="feature">
                        <div class="feature-icon">🏋️‍♂️</div>
                        <div class="feature-title">Track Workouts</div>
                        <div class="feature-description">Log your workouts, set goals, and track your progress over time.</div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="feature">
                        <div class="feature-icon">📈</div>
                        <div class="feature-title">View Statistics</div>
                        <div class="feature-description">Visualize your fitness data with detailed statistics and charts.</div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="feature">
                        <div class="feature-icon">💬</div>
                        <div class="feature-title">Join Community</div>
                        <div class="feature-description">Connect with others, share achievements, and get inspired.</div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="testimonials py-5">
        <div class="container text-center">
            <h2>What Our Users Say</h2>
            <div class="testimonial">
                <p>"I love using this fitness tracker! It keeps me accountable and motivated every day."</p>
                <div class="testimonial-author">- Sarah M.</div>
            </div>
            <div class="testimonial">
                <p>"Highly recommend! The analytics are fantastic for monitoring my progress."</p>
                <div class="testimonial-author">- John D.</div>
            </div>
        </div>
    </section>
{% endblock %}

myApp/templates/log_pr.html
{% extends "base.html" %}

{% block title %}PR Log{% endblock %}

{% block content %}
    <head>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/logPr.css') }}">
    </head>
    <body>
        <div class="container">
            <h1>Log Personal Record (PR)</h1>
            <form method="POST" action="{{ url_for('user_bp.log_pr') }}">
                <div class="form-group">
                    <label for="name">Exercise Name:</label>
                    <input type="text" id="name" name="name" class="form-control" required>
                </div>
                
                <div class="form-group">
                    <label for="weight">Weight:</label>
                    <input type="number" id="weight" name="weight" class="form-control">
                </div>
                
                <div class="form-group">
                    <label for="unit">Unit:</label>
                    <select id="unit" name="unit" class="form-control">
                        <option value="kg">kg</option>
                        <option value="lb">lb</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="date" id="date" name="date" class="form-control">
                </div>
                
                <button type="submit" class="btn btn-primary">Log PR</button>
            </form>
            <br>
            <a href="{{ url_for('user_bp.user') }}" class="btn btn-secondary">Back to Profile</a>
        </div>
        <script src="{{ url_for('static', filename='js/logPr.js') }}"></script>
    </body>
{% endblock %}

myApp/templates/login.html
{% extends "base.html" %}
{% block title %}Login page{% endblock %}

{% block content %}
<body>
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
        <div class="card mt-5">
            <div class="card-header text-center">
            <h3>Login</h3>
            </div>
            <div class="card-body">
            <form action="/login/" method="POST">
                <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
                </div>
                <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>
            </div>
            <div class="card-footer text-center">
            <a href="/signup/">Don't have an account? Sign up</a>
            </div>
        </div>
        </div>
    </div>
    </div>

</body>
{% endblock %}

myApp/templates/pr_chart.html
{% extends "base.html" %}

{% block title %}
PR Progression
{% endblock %}

{% block content %}
<div class="container my-4">
    <h1>PR Progression</h1>
    <div class="mb-3">
        <label for="exercise-select" class="form-label">Select Exercise:</label>
        <select id="exercise-select" class="form-select">
            <!-- Options will be populated here -->
        </select>
    </div>
    <canvas id="prChart" width="100" height="100"></canvas>
</div>
<style>
    #prChart {
        width: 100%; /* Make the chart responsive */
        max-width: 600px; /* Set a maximum width */
        height: 400px; /* Set a fixed height */
        margin: auto; /* Center align the chart */
        border: 1px solid #ddd; /* Optional border */
        border-radius: 8px; /* Optional rounded corners */
    }
    </style>    

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0"></script>
<script src="{{ url_for('static', filename='js/pr_chart.js') }}"></script>
{% endblock %}

myApp/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Create an Account</h2>
    <form action="{{ url_for('user_bp.signup') }}" method="post">
        <div class="mb-3">
            <label for="name" class="form-label">User name</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="username" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="supersecretpassword" required>
        </div>
        
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
    <p class="mt-3">Already have an account? <a href="{{ url_for('user_bp.login') }}">Log in</a></p>
</div>
{% endblock %}

myApp/templates/test.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
<h1>Test</h1>
{% endblock %}

myApp/templates/view.html
{% extends "base.html" %}
{% block title %}View all users{% endblock %}
{% block content %}
    {% for user in users %}
        <p>Username: {{ user.username }}, Email: {{ user.email }}</p>
        <form action="{{ url_for('user_bp.delete_user', user_id=user._id) }}" method="post">
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        <hr>
    {% endfor %}
{% endblock %}

myApp/templates/viewExercises.html
{% extends "base.html" %}
{% block content %}

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/viewExercises.css') }}">
</head>
<div class="container mt-4">
    <h1>Your Logged Exercises</h1>

    {% if exercises %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Weight</th>
                    <th>Date Logged</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for exercise in exercises %}
                    <tr>
                        <form method="POST" action="{{ url_for('user_bp.view_exercises') }}">
                            <input type="hidden" name="exercise_id" value="{{ exercise._id }}">
                            <td><input type="text" name="name" value="{{ exercise.name }}" class="form-control"></td>
                            <td><input type="text" name="description" value="{{ exercise.description }}" class="form-control"></td>
                            <td><input type="number" step="any" name="weight" value="{{ exercise.weight or '' }}" class="form-control"></td>
                            <td>{{ exercise.date.strftime('%Y-%m-%d') }}</td>
                            <td>
                                <button type="submit" name="update" class="btn btn-success">Update</button>
                                <button type="submit" name="delete" class="btn btn-danger">Delete</button>
                            </td>
                        </form>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info" role="alert">
            You have not logged any exercises yet.
        </div>
    {% endif %}

    <a class="btn btn-primary mt-3" href="{{ url_for('user_bp.create_exercise') }}">Log a New Exercise</a>
</div>
{% endblock %}

myApp/templates/view_prs.html
{% extends "base.html" %}

{% block title %}View Records{% endblock %}

{% block content %}
    <div class="container">
        <h1>View Personal Records (PRs)</h1>
        {% if prs %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Exercise</th>
                        <th>Weight</th>
                        <th>Unit</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pr in prs %}
                        <tr>
                            <td>{{ pr.exercise_name }}</td>
                            <td>{{ pr.weight }}</td>
                            <td>{{ pr.unit }}</td>
                            <td>{{ pr.date.strftime('%Y-%m-%d') }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No personal records found.</p>
        {% endif %}
        <a href="{{ url_for('user_bp.log_pr') }}" class="btn btn-primary">Log New PR</a>
        <a href="{{ url_for('user_bp.user') }}" class="btn btn-secondary">Back to Profile</a>
    </div>
{% endblock %}

myApp/templates/view_workoutPlan.html
{% extends "base.html" %}

{% block title %}Workout Plans{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Your Workout Plans</h2>
    <div class="row">
        {% for plan in plans %}
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h4>{{ plan.name }}</h4>
                </div>
                <div class="card-body">
                    <p><strong>Cycle Type:</strong> {{ plan.cycle_type }}</p>
                    <p><strong>Cycle Length:</strong> {{ plan.cycle_length }} days</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myApp/templates/view_workoutPlans.html
{% extends "base.html" %}

{% block title %}
Workout Plans
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Your Workout Plans</h2>
    <div class="row">
        {% for plan in plans %}
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h4>{{ plan.name }}</h4>
                </div>
                <div class="card-body">
                    <p><strong>Cycle Type:</strong> {{ plan.cycle_type }}</p>
                    <p><strong>Cycle Length:</strong> {{ plan.cycle_length }} days</p>
                    <a href="{{ url_for('user_bp.edit_workoutPlan', plan_id=plan._id) }}" class="btn btn-primary">View & Edit</a>  <!--  REMEMBER TO CHANGE THIS LINE PLEASE -->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}